version = "1.1.13"

[format]
workspace = "{id}{delim}<span color='#ffffffcc'><big>{clients}</big></span>"
client = "{icon}"
client_active = "{icon}"

[class]
"DEFAULT"               = "\U0000f2d0"

"blueberry"             = "\U000f00af"
"foot"                  = "\U0000f489"
"imv"                   = "\U0000f03e"
"luakit"                = "\U000f059f"
"lite-xl"               = "\U000f0169"
"mpv"                   = "\U000f0567"
"zathura"               = "\U000f0219"
"iwgtk"                 = "\U000f05a9"
"pavucontrol"           = "\U0000f028"
"pcmanfm"               = "\U000f0770"

"blender"               = "\U000f00ab"
"chrome"                = "\U0000e743"
"code"                  = "\U000f0a1e"
"discord"               = "\U000f066f"
"firefox"               = "\U000f0239"
"(?i)gimp"              = "\U000f11e3"
"mcpelauncher"          = "\U000f0373"
"pithos"                = "\U000f03db"
"steam"                 = "\U0000f1b6"

"teams.microsoft.com"   = "\U000f02bb"
"outlook.office.com"    = "\U000f0d22"
"word.office.com"       = "\U000f1392"
"microsoft-edge"        = "\U000f01e9"

[exclude]
"" = "^$"
