#!/bin/sh
source=Vimix-cursors
output=Vimix-white-hyprcursors

src="$source/src"
dst="$output/hyprcursors"

rm -rf "$output"
mkdir -p "$dst"

cat > "$output/manifest.hl" <<END
name = Vimix Cursors - White
description = https://github.com/vinceliuice/Vimix-cursors
version = 2020-02-24
cursors_directory = hyprcursors
END

fmt='[0-9]+ ([0-9]+) ([0-9]+) x1\/(.+)\.png ?([0-9]+)?'
for cursor in "$src/config"/*.cursor; do
    name=$(basename "$cursor" .cursor)
    meta="$dst/$name/meta.hl"
    mkdir "$dst/$name"

    first=$(grep -m1 '^24' "$cursor")
    x=$(echo "$first" | sed -E "s/$fmt/\1/")
    y=$(echo "$first" | sed -E "s/$fmt/\2/")
    echo "hotspot_x = $(awk "BEGIN { print $x/64 }")" >> "$meta"
    echo "hotspot_y = $(awk "BEGIN { print $y/64 }")" >> "$meta"

    sed -n "/$name/s/ .*//p" $src/cursorList | while read line ; do
        echo "define_override = $line" >> "$meta"
    done

    grep '^24' "$cursor" | while read line ; do
        f=$(echo "$line" | sed -E "s/$fmt/\3/")
        t=$(echo "$line" | sed -E "s/$fmt/\4/")
        cp "$src/svg-white/$f.svg" "$dst/$name"
        echo "define_size = 24, $f.svg${t:+", $t"}" >> "$meta"
    done
done
