#!/bin/sh
if $(case $1 in
    on)
        true
        ;;
    off)
        false
        ;;
    *)
        hyprctl monitors all -j \
        |   jq -e '.[] | select(.name == "eDP-1") | .disabled'
        ;;
esac); then
    hyprctl reload
else
    hyprctl keyword monitor eDP-1,disable
fi
