#!/bin/sh
JQ='.[] | select(.model == "HP 25x").name'
OUTPUT=$(hyprctl -j -i 0 monitors | jq -r "$JQ" | tr - _)
exec busctl --user set-property \
    rs.wl-gammarelay /outputs/$OUTPUT rs.wl.gammarelay Gamma d 1.25
