#!/bin/sh
systemd-cat systemd-inhibit --what=idle \
    wayvnc -go $1 $(tailscale ip -1) &
loginctl unlock-session
wayvncctl -wj event-receive | while IFS= read -r e; do
    case $(echo "$e" | jq -r .method) in
        wayvnc-startup) systemd-notify --ready ;;
        client-disconnected) wayvncctl wayvnc-exit; break ;;
        wayvnc-shutdown) break ;;
    esac
done
loginctl lock-session
wait
