#!/bin/sh
SCRIPT=$(cd "$(dirname "$0")" && pwd)
. $SCRIPT/.zshenv

setup_dir() { mkdir -p $1 && cd $1; }

(setup_dir $XDG_BIN_HOME
    for BIN in $SCRIPT/.bin/*; do ln -s $BIN; done
)

(setup_dir $XDG_CONFIG_HOME
    for CONFIG in $SCRIPT/.config/*; do ln -s $CONFIG; done
)

(setup_dir $XDG_DATA_HOME
    link_data() (setup_dir $1
        for DATA in $2; do ln -s $SCRIPT/.data/$1/$DATA; done
    )
    git clone https://github.com/scopatz/nanorc nano
    link_data tmux "theme.conf"
    link_data zsh/rc "color.zsh highlight.zsh prompt.zsh title-path.zsh"
)

(setup_dir .ssh
    ln -s $SCRIPT/.ssh/config
)

ln -s $SCRIPT/.zshenv

chsh -s /bin/zsh
