#!/bin/sh
case $1 in
    cruft)
        [ "$2" = "all" ] && FILTER="" || FILTER="|/boot|/nix|/var"
        cruft-ng | grep -Ev "^ +([^ /]$FILTER)"
        ;;
    files)
        debsums -acs
        ;;
    packages)
        [ "$2" = "all" ] && FILTER="" || FILTER="!~R~i"
        aptitude search "(!~poptional !~pextra !~i | (~poptional | ~pextra) ~i) !~slibs !~v $FILTER"
        ;;
    circular)
        check packages all | sed -En 's/^i .? ([^ ]+).*$/\1/p' | while read pkg; do
            rdepends --installed --recurse $pkg | grep -q " $pkg$" && echo $pkg
        done
        ;;
esac
