#!/bin/sh
case $1 in
    on)
        TAB="keyword bindl ,tab,execr,sudo chvt 3"
        ESC="keyword bindl ,escape,dpms,toggle eDP-1"
        hyprctl --batch "$TAB ; $ESC"
        ;;
    off)
        TAB="keyword unbind ,tab"
        ESC="keyword unbind ,escape"
        hyprctl --batch "$TAB ; $ESC"
        ;;
esac
