#!/bin/sh
GAME=${2:-$(find -type d | tr -d '\n' | sed 's_\.\./__;s_\./_|_g')}
gog() {
    lgogdownloader \
        --platform w \
        --no-subdirectories \
        --game "^($GAME)$" \
        --include i \
        "$@"
}
case $1 in
  pull)
    gog --download
    ;;
  clean)
    gog --check-orphans --delete-orphans
    ;;
  check)
    gog --status --size-only | grep -v ^OK
    ;;
  verify)
    gog --status | grep -v ^OK
    ;;
  repair)
    gog --repair --download
    ;;
esac
