[buildPlans.iosevka-clecompt]
family = "Iosevka CEL"
spacing = "fixed"
serifs = "sans"

[buildPlans.iosevka-clecompt.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
y = "cursive"
long-s = "flat-hook-tailed"
lower-xi = "rounded"
zero = "slashed"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "closed-contour"
asterisk = "penta-low"
underscore = "above-baseline"
percent = "rings-continuous-slash"

[buildPlans.iosevka-clecompt.widths.normal]
shape = 625
menu = 5
css = "normal"

[buildPlans.iosevka-clecompt.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
