[matching]
'imv'                   = "\U0000f03e"
'org.twosheds.iwgtk'    = "\U000f05a9"
'luakit'                = "\U000f059f"
'mpv'                   = "\U000f0567"
'pcmanfm'               = "\U000f0770"
