fallback                = "<span font='Symbols Nerd Font 12'>\U0000f2d0</span>"

[matching]
'blueberry.py'          = "<span font='Symbols Nerd Font 12'>\U000f00af</span>"
'foot'                  = "<span font='Symbols Nerd Font 12'>\U0000f489</span>"
'imv'                   = "<span font='Symbols Nerd Font 12'>\U0000f03e</span>"
'luakit'                = "<span font='Symbols Nerd Font 12'>\U000f059f</span>"
'lite-xl'               = "<span font='Symbols Nerd Font 12'>\U000f0169</span>"
'mpv'                   = "<span font='Symbols Nerd Font 12'>\U000f0567</span>"
'org.twosheds.iwgtk'    = "<span font='Symbols Nerd Font 12'>\U000f05a9</span>"
'pavucontrol'           = "<span font='Symbols Nerd Font 12'>\U0000f028</span>"
'pcmanfm'               = "<span font='Symbols Nerd Font 12'>\U000f0770</span>"

'code-url-handler'      = "<span font='Symbols Nerd Font 12'>\U000f0a1e</span>"
