icons_format = "<span font='Symbols Nerd Font 12'>{icon}</span>"

[theme]
theme = "native"

[icons]
icons = "material-nf"
[icons.overrides]
volume_muted = "\U000f0581"

[[block]]
block = "custom"
format = "<span font='Symbols Nerd Font 12' color='#ffffff33'>\U000f1398</span>"
command = ""
interval = "once"
[[block.click]]
button = "left"
cmd = "swaymsg kill"

[[block]]
block = "focused_window"
format = "$title|"

[[block]]
block = "sound"
format = "$icon"
device_kind = "sink"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
format = "$icon"
device_kind = "source"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = "$icon"
inactive_format = "$icon"
missing_format = "\u00d7"
[[block.click]]
button = "left"
cmd = "iwgtk"

[[block]]
block = "battery"
driver = "upower"
format = "$icon"
full_format = "$icon"
charging_format = "$icon"
empty_format = "$icon!"
not_charging_format = "$icon"
missing_format = "$icon"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%I:%M %p')"

[[block]]
block = "notify"
format = "$icon{($notification_count.eng(w:1))|} "
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
