#!/bin/sh
case $1 in
    cruft)
        [ "$2" = "all" ] && FILTER="" || FILTER="|/boot|/var"
        cruft-ng | grep -Ev "^ +([^ /]$FILTER)"
        ;;
    files)
        debsums -acs
        ;;
    packages)
        [ "$2" = "all" ] && FILTER="" || FILTER="!~R~i"
        aptitude search "(!~poptional !~pextra !~i | (~poptional | ~pextra) ~i) !~slibs !~v $FILTER"
        ;;
esac
