#!/bin/sh
case $1 in
    cruft)
        if [ "$2" = "all" ]
        then
            cruft --ignore "/home /mnt"
        else
            cruft --ignore "/boot /home /mnt /tmp /sys /var"
        fi
        ;;
    files)
        debsums -acs
        ;;
    installed)
        if [ "$2" = "all" ]
        then
            aptitude search '(~poptional|~pextra) ~i !~slibs'
        else
            aptitude search '(~poptional|~pextra) ~i !~R~i'
        fi
        ;;
    missing)
        aptitude search '!~poptional !~pextra !~slibs !~v !~i'
        ;;
esac
