#!/bin/sh
if [ -d $2 ]
then
    SRC=$2
else
    SRC=ssh.clecompt.link:$2
fi
ARGS="$SRC/ . -avz --delete"
case $1 in
    time)
        rsync $ARGS
        ;;
    size)
        rsync $ARGS --size-only
        ;;
    hash)
        rsync $ARGS --checksum
        ;;
esac
