#!/bin/sh
if [ -d "$2" ]
then
    SRC="$2"
else
    SRC="server:$2"
fi
ARGS=". -avz --delete"
case $1 in
    time)
        rsync "$SRC/" $ARGS
        ;;
    size)
        rsync "$SRC/" $ARGS --size-only
        ;;
    hash)
        rsync "$SRC/" $ARGS --checksum
        ;;
esac
